export const LEADION_TOKENS = {
  colors: {
    primary: '#635BFF',
    primaryHover: '#5046E5',
    primaryLight: '#EEF0FF',
    ink: '#111318',
    inkSecondary: '#475467',
    inkMuted: '#68707D',
    background: '#F7F8FA',
    surface: '#FFFFFF',
    border: '#E6E8EC',
    secondary: '#68707D',
    success: '#16A34A',
    warning: '#D97706',
    danger: '#DC2626',
    info: '#2563EB',
  },
  typography: {
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    display: {
      mobile: 'text-[28px] leading-tight font-bold tracking-tight',
      desktop: 'sm:text-[32px] sm:leading-tight sm:font-bold',
    },
    h1: {
      mobile: 'text-[24px] leading-snug font-bold tracking-tight',
      desktop: 'sm:text-[28px] sm:leading-snug sm:font-bold',
    },
    h2: {
      mobile: 'text-[20px] leading-snug font-semibold tracking-tight',
      desktop: 'sm:text-[22px] sm:leading-snug sm:font-semibold',
    },
    h3: {
      mobile: 'text-[18px] leading-snug font-semibold tracking-tight',
      desktop: 'sm:text-[18px]',
    },
    bodyLarge: 'text-[16px] leading-relaxed font-normal',
    body: 'text-[14px] leading-normal font-normal',
    bodyMedium: 'text-[14px] leading-normal font-medium',
    caption: 'text-[12px] leading-normal font-normal',
    label: 'text-[12px] leading-tight font-medium',
    button: 'text-[14px] leading-none font-semibold',
  },
  numeric: {
    small: 'text-[14px] font-semibold tabular-nums tracking-tight',
    medium: 'text-[18px] sm:text-[20px] font-semibold tabular-nums tracking-tight',
    large: 'text-[24px] sm:text-[28px] font-bold tabular-nums tracking-tight',
    hero: 'text-[32px] sm:text-[40px] font-bold tabular-nums tracking-tight',
  },
  sizing: {
    buttonMinHeightMobile: 'min-h-[44px]',
    buttonPreferredHeightMobile: 'h-12',
    inputMinHeightMobile: 'min-h-[48px]',
    touchTargetMin: 'min-w-[44px] min-h-[44px]',
  },
  spacing: [4, 8, 12, 16, 20, 24, 32, 40, 48, 64],
  radius: {
    inputs: '11px',
    cards: '15px',
    modals: '20px',
  },
  channels: {
    whatsapp: {
      name: 'WhatsApp',
      color: '#16A34A',
      bgColor: '#F0FDF4',
      badgeClass: 'bg-emerald-50 text-emerald-700 dark:bg-emerald-950/50 dark:text-emerald-300 border-emerald-200 dark:border-emerald-800/60',
    },
    linkedin: {
      name: 'LinkedIn',
      color: '#0A66C2',
      bgColor: '#EFF6FF',
      badgeClass: 'bg-blue-50 text-blue-700 dark:bg-blue-950/50 dark:text-blue-300 border-blue-200 dark:border-blue-800/60',
    },
    email: {
      name: 'E-mail',
      color: '#4B5563',
      bgColor: '#F3F4F6',
      badgeClass: 'bg-zinc-100 text-zinc-800 dark:bg-zinc-800/60 dark:text-zinc-200 border-zinc-200 dark:border-zinc-700',
    },
    phone: {
      name: 'Telefone',
      color: '#635BFF',
      bgColor: '#EEF0FF',
      badgeClass: 'bg-indigo-50 text-indigo-700 dark:bg-indigo-950/50 dark:text-indigo-300 border-indigo-200 dark:border-indigo-800/60',
    },
  },
} as const;
